# Generated by Django 4.2.3 on 2023-07-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumart', models.URLField(max_length=2000)),
                ('artists', models.CharField(max_length=500)),
                ('duration', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('preview_url', models.URLField(max_length=2000)),
                ('track_number', models.SmallIntegerField()),
                ('uri', models.URLField(max_length=2000)),
            ],
        ),
    ]
